[language-server.typescript-language-server.inlayHints]
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayFunctionParameterTypeHints = true
includeInlayVariableTypeHints = true
includeInlayVariableTypeHintsWhenTypeMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayEnumMemberValueHints = true

[language-server.glas]
command = "/Users/douglasmassolari/.vscode/extensions/maurobalbi.glas-vscode-0.0.6-darwin-arm64/glas"
args = ["--stdio"]

[[language]]
name = "gleam"
language-servers = ["glas", "gleam"]
