[language-server.typescript-language-server.inlayHints]
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayFunctionParameterTypeHints = true
includeInlayVariableTypeHints = true
includeInlayVariableTypeHintsWhenTypeMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayEnumMemberValueHints = true
