-- Duplique esse arquivo e renomeie a cópia para init.lua
-- Coloque suas configurações personalizadas aqui
--
--
-- Para desabilitar alguma source do cmp, adicione a source table vim.g.disable_cmp_sources
--
-- Por exemplo:
-- vim.g.disable_cmp_sources = { 'cmp_tabnine' }
