default_profile = "douglas"

[profiles.douglas]
user_id = "@douglas:massolari.us.to"
url = "https://massolari.us.to"

[profiles.dougmass]
user_id = "@dougmass:matrix.org"
url = "https://matrix.org"

[profiles.beeper]
user_id = "@douglas-massolari:beeper.com"
url = "https://matrix.beeper.com"

[settings]
image_preview = {}
username_display = "displayname"

[settings.notifications]
enabled = true

[macros."normal|visual"]
"V" = "<C-W>m"
"<C-L>" = "<C-W>l"
"<C-H>" = "<C-W>h"
"<C-J>" = "<C-W>j"
"<C-K>" = "<C-W>k"
"<C-M>" = "<CR>"
"j" = "gj"
"k" = "gk"
"\\h" = "<C-W>s"
"\\v" = "<C-W>v"
"\\q" = "<C-W>q"
"gh" = "0"
"gs" = "_"
"gl" = "$"
"ge" = "G"
"gp" = "\"+p"

[macros.normal]
" " = "\\"
"gc" = ":chats<CR>"
"\\a" = ":react "
"\\e" = ":edit<CR>"
"\\o" = ":open<CR>"
"\\r" = ":reply<CR>"
"\\m" = "<CR><C-O>"
"<C-C>" = ":cancel!<CR>"
