# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

function setup_hm_session_vars;
# Only source this once.
if [ -n "$__HM_SESS_VARS_SOURCED" ]
  return
end
set -gx __HM_SESS_VARS_SOURCED '1'
set -gx STARSHIP_CONFIG '/Users/douglasmassolari/.config/starship.toml'
set -gx MANPAGER 'nvim +Man!'
end

setup_hm_session_vars

set PATH \
    $HOME/.cargo/bin \
    $HOME/.docker/bin \
    $HOME/.ghcup/bin \
    $HOME/.local/bin \
    $HOME/.local/share/nvim/mason/bin \
    $HOME/.nimble/bin \
    $HOME/.nix-profile/bin \
    $HOME/go/bin \
    /nix/var/nix/profiles/default/bin \
    /opt/homebrew/bin \
    /usr/local/bin \
    /opt/homebrew/opt/openjdk/bin \
    $PATH

function fish_user_key_bindings
    # Execute this once per mode that emacs bindings should be used in
    fish_default_key_bindings -M insert

    # Then execute the vi-bindings so they take precedence when there's a conflict.
    # Without --no-erase fish_vi_key_bindings will default to
    # resetting all bindings.
    # The argument specifies the initial mode (insert, "default" or visual).
    fish_vi_key_bindings --no-erase insert
end

set -g fish_key_bindings fish_user_key_bindings
set -x DYLD_LIBRARY_PATH /opt/homebrew/lib
set -x XDG_CONFIG_HOME $HOME/.config
set -x EDITOR nvim

abbr --add lg lazygit
abbr --add karabiner-daemon "sudo '/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon'"

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    fzf --fish | source
    # tv init fish | source
    # Abbreviations

    # Aliases
    alias ls='lsd'

    # Interactive shell initialisation
    zoxide init fish | source

    if test "$TERM" != dumb
        starship init fish | source
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/douglasmassolari/.local/share/fish/home-manager_generated_completions" $post
    end

    carapace _carapace fish | source

    direnv hook fish | source

end

function yy
    set -l tmp (mktemp -t "yazi-cwd.XXXXX")
    command yazi $argv --cwd-file="$tmp"
    if read cwd <"$tmp"; and [ -n "$cwd" ]; and [ "$cwd" != "$PWD" ]
        builtin cd -- "$cwd"
    end
    rm -f -- "$tmp"
end

function hm_remove_generations
  home-manager generations | fzf -n 5,7 -m --accept-nth=5 --prompt='Select generations to remove: ' | xargs -I {} home-manager remove-generations {}
end
