-- Which-key
-- vim.g.which_key_leader_map = {
-- }
--
-- vim.g.which_key_g_map = {
--   d = 'Ir para definição',
--   i = 'Ir para implementação',
--   y = 'Ir para definição do tipo',
--   r = 'Ver referências',
-- }
--
-- vim.g.which_key_closing_brackets_map = {
--   [']'] = 'Próxima função Elm',
--   d = 'Próximo problema',
--   e = 'Próximo erro',
-- }
--
-- vim.g.which_key_open_brackets_map = {
--   ['['] = 'Função Elm anterior',
--   d = 'Problema anterior',
--   e = 'Erro anterior'
-- }
--
-- vim.fn['which_key#register']('<Space>', 'g:which_key_leader_map')
-- vim.fn['which_key#register']('g', 'g:which_key_g_map')
-- vim.fn['which_key#register'](']', 'g:which_key_closing_brackets_map')
-- vim.fn['which_key#register']('[', 'g:which_key_open_brackets_map')
